### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by ghost** [fcfangcc/django-editor-md#1]
指向“http://127.0.0.1:8000/static/editor.md/lib/marked.min.js”的 <script> 加载失败。
edit_test:8
指向“http://127.0.0.1:8000/static/editor.md/lib/prettify.min.js”的 <script> 加载失败。
edit_test:9
指向“http://127.0.0.1:8000/static/editor.md/lib/raphael.min.js”的 <script> 加载失败。
edit_test:10
指向“http://127.0.0.1:8000/static/editor.md/lib/underscore.min.js”的 <script> 加载失败。
edit_test:11
指向“http://127.0.0.1:8000/static/editor.md/lib/sequence-diagram.min.js”的 <script> 加载失败。
edit_test:12
指向“http://127.0.0.1:8000/static/editor.md/lib/flowchart.min.js”的 <script> 加载失败。
edit_test:13
指向“http://127.0.0.1:8000/static/editor.md/lib/jquery.flowchart.min.js”的 <script> 加载失败。
edit_test:14
指向“http://127.0.0.1:8000/static/editor.md/lib/codemirror/codemirror.min.js”的 <script> 加载失败。
edit_test:1

**Comment by fcfangcc** [comment]
我试了下没问题啊，是怎么报错的

**Comment by albus12138** [comment]
缺少 static/editor.md/lib 文件夹，从[官网](https://pandao.github.io/editor.md/)下载，然后把里面的lib文件夹贴进去就好了
